name: Metrics
on:
  # Schedule updates (once a day)
  schedule: [{cron: "0 0 * * *"}]
  # Run manually
  workflow_dispatch:
  # Run on each push to main branch
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # UPDATED: Use the custom token to see private repos
          token: ${{ secrets.METRICS_TOKEN }}
          user: bisquitew
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Bucharest
          
          # Plugin: Languages
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          
          # Plugin: Repositories
          plugin_repositories: yes
          plugin_repositories_featured: bisquitew/SAT, bisquitew/p3marketplaceproject
          plugin_repositories_order: featured
          plugin_repositories_pinned: 0
