name: Metrics
on:
  # Schedule updates (once a day)
  schedule: [{cron: "0 0 * * *"}]
  # Run manually
  workflow_dispatch:
  # Run on each push to main branch
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: bisquitew
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Bucharest
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
